### ISSUE TITLE
Add announcement div at top of page

### ISSUE THREAD

**Issue by ardalis** [ardalis/DevIQ-gatsby#13]
Initial version can be static for site.

Eventually I'd like to be able to change it per section (design patterns, ddd, etc.)

Something like this:
![image](https://user-images.githubusercontent.com/782127/108373972-74b2ab00-71ce-11eb-9b4d-73b560ec6533.png)

**Comment by ardalis** [comment]
Would be nice if it has an 'x' to hide it but not required.

**Comment by ardalis** [comment]
Sure, how about
"Learn more about Design Patterns in this overview course by Steve Smith on Pluralsight"
linking here:
https://www.pluralsight.com/courses/design-patterns-overview

**Comment by sadukie** [comment]
Initial version is in - see #104 and #105 

This part is still open:

```
Eventually I'd like to be able to change it per section (design patterns, ddd, etc.)
```
