### ISSUE TITLE
The guard statements can be more explicit

### ISSUE THREAD

**Issue by StingyJack** [ardalis/DevIQ-gatsby#157]
Assuming the code depicted is c#, this guard clause 

``` csharp
 if (user == null)
    {
        throw new ArgumentNullException(nameof(user));
    }
```

can be written as 

``` csharp
_ = user ?? throw new ArgumentNullException(nameof(user));
```
... and avoid hiding the behavior of the guard in another function, like this does...

``` csharp
 Guard.AgainstNull(user, nameof(user));
```
Resharper's live templates or VS snippets make creating these statements an easy experience. 

For strings an extension method that returns null if the string is null or whitespace means the discard based pattern can be used for strings. 
The same can be done for empty collections

**Comment by ardalis** [comment]
The Guard library isn't so much hiding behavior as ensuring consistency throughout the codebase. (well, ok, both can be true)

It also supports many other tests beyond just null checks as well as inline assignment. For example:

```csharp
_firstName = Guard.Against.NullOrWhiteSpace(firstName, nameof(firstName));
_quantity = Guard.Against.NegativeOrZero(quantity, nameof(quantity));
_address = Guard.Against.InvalidAddress(address, nameof(address));
_order = Guard.Against.Null(order, nameof(order));
```

This consistency results in very readable code, which results in fewer bugs, IME.

See also: https://www.youtube.com/watch?v=Tvx6DNarqDM for another take
