### ISSUE TITLE
Implement a collapsing menu since it's getting rather long

### ISSUE THREAD

**Issue by ardalis** [ardalis/DevIQ-gatsby#164]
The left nav menu should support expanding and collapsing each section in the browser.

**Comment by bricejordan15** [comment]
I'll give it a shot :)

**Comment by ardalis** [comment]
Go for it! I'm not sure if there are any components that help or updated docs theme (which would be preferred) but even a hardcoded solution will help, thanks!

**Comment by sadukie** [comment]
@bricejordan15 Are you still looking into the collapsing menu? If so, need any help?
