### ISSUE TITLE
Add support for C# code highlighting

### ISSUE THREAD

**Issue by ilyanaDev** [ardalis/DevIQ-gatsby#2]
Repo currently uses Prism-React-Renderer for code highlighting, which does not natively support C#. I tried commenting out all references to prism-react-renderer and to react-live (which it is a part of) in the json files, and installing prism.js (which does support C#), but this did not change the behavior

**Comment by ardalis** [comment]
Oh, this is probably why I saw a bunch of java in the code fences. Yeah we should get a highlighter working that supports C#. Maybe the one I'm using in my blog could be made to work?
