### ISSUE TITLE
Update Google Analytics for new gtags

### ISSUE THREAD

**Issue by sadukie** [ardalis/DevIQ-gatsby#236]
I see this site uses gatsby-plugin-google-analytics.  We might want to look into migrating to gtag based on the deprecation notice here: https://www.gatsbyjs.com/plugins/gatsby-plugin-google-analytics/

**Comment by ardalis** [comment]
Maybe @KyleMcMaster can work on this since he has just done it for NimblePros

**Comment by KyleMcMaster** [comment]
@ardalis I'm happy to add the configuration based on the NP blog at some point this week (likely Friday)
