### ISSUE TITLE
Anderson's Law

### ISSUE THREAD

**Issue by ardalis** [ardalis/DevIQ-gatsby#248]
![image](https://github.com/ardalis/DevIQ-gatsby/assets/782127/3a70749d-aa58-4723-a34e-e2278dd62e24)

Cited here: https://youtu.be/FyCYva9DhsI?si=sq6IylyM-db9SmNw&t=1043

Not seeing it anywhere online, though...

**Comment by sadukie** [comment]
See also: https://www.reddit.com/r/quotes/comments/39n8mz/i_have_yet_to_see_any_problem_however_complicated/

And:  https://quoteinvestigator.com/2015/06/15/complicated/
