### ISSUE TITLE
Laws: Rules of Simple Design

### ISSUE THREAD

**Issue by ardalis** [ardalis/DevIQ-gatsby#263]
Not exactly a "law" but still good to include.

Reference:
https://martinfowler.com/bliki/BeckDesignRules.html

**Comment by sadukie** [comment]
@ardalis These are already covered in [Simple Design](https://github.com/ardalis/DevIQ-gatsby/blob/main/src/docs/practices/simple-design.md). I noticed that this morning while updating the featured images.

Do you want this reclassified as a law? Do you want them split into multiple articles? Is the practice page enough?
