### ISSUE TITLE
Add Object Mother pattern

### ISSUE THREAD

**Issue by ardalis** [ardalis/DevIQ-gatsby#284]
See: https://martinfowler.com/bliki/ObjectMother.html

I've always thought this was a pretty stupid name but others will search for it so we should include it. It's just a factory or builder, and folks should call it that, IMO...

**Comment by sadukie** [comment]
It's a sandwich between the factory and builder. It's built on top of factories. I don't see this used often, but it's a stepping ground for going to builder.  Personally, I prefer builders in tests and wouldn't use object mothers. 🤷🏻‍♀️
