### ISSUE TITLE
Add Rule Engine Pattern

### ISSUE THREAD

**Issue by ardalis** [ardalis/DevIQ-gatsby#289]
Link to Pluralsight course.

Include this info:
Q: Is it violating Open Closed principle if the rule returns a value that includes extra information (whether or not rules are short circuited) (I've got a combination of First match and aggregation)

A: No that’s probably fine. If your engine code gets too complex maybe you create types representing the different kinds of rules and/or their results that let you Replace Conditional with Polymorphism.

Q: In the case of ordered rules, is it wrong to pass (and change) contextual information from one rule to the next?

A: Not wrong but makes me think Chain of Responsibility might be a good fit.

(and make sure Chain of Responsibility is in our pattern list as well) #290

**Comment by sadukie** [comment]
[Pluralsight course](https://app.pluralsight.com/library/courses/c-sharp-design-patterns-rules-pattern/table-of-contents)
