### ISSUE TITLE
Chain of Responsibility Pattern

### ISSUE THREAD

**Issue by ardalis** [ardalis/DevIQ-gatsby#290]
Mention use with
- ASP.NET Core Middleware
- MediatR and pipeline behaviors

and its importance for pulling out cross-cutting concerns (and following Separation of Concerns, SRP)

**Comment by ardalis** [comment]
See #250

**Comment by sadukie** [comment]
Add link to this? https://www.youtube.com/watch?v=eSQHpfaYspw

**Comment by ardalis** [comment]
Sure, though eventually I'll have my own as well.
