### ISSUE TITLE
Add Tools Page

### ISSUE THREAD

**Issue by KyleMcMaster** [ardalis/DevIQ-gatsby#299]
I noticed the other sections have their own dedicated pages which you can navigate to subtopics from. Tools is missing this page but has topics beneath it so it'd be worth adding a page for listing those individual items on. 

![image](https://github.com/ardalis/DevIQ-gatsby/assets/11415127/cf10bcdd-c397-4e70-a00f-63c8c2e83fa8)

**Comment by ardalis** [comment]
Sure, go for it if you like.
