### ISSUE TITLE
Add Terms Page

### ISSUE THREAD

**Issue by KyleMcMaster** [ardalis/DevIQ-gatsby#300]
I noticed the other sections have their own dedicated pages which you can navigate to subtopics from. Terms is missing this page but has topics beneath it so it'd be worth adding a page for listing those individual items on.

![image](https://github.com/ardalis/DevIQ-gatsby/assets/11415127/acf71569-00a0-471d-82b7-8010a9b3375d)

**Comment by ardalis** [comment]
Sure, go for it if you like.
