### ISSUE TITLE
Question on Patterns organization

### ISSUE THREAD

**Issue by sadukie** [ardalis/DevIQ-gatsby#316]
@ardalis With the growth in pattern ideas, do all of these get put in design patterns?  Do we break them up to something like Design Patterns, Data Patterns, and Testing Patterns?

For example, I want to include some of the data patterns that I am used to working with, but they are specifically related towards data.

#315 mentions a pattern that is specifically to testing.

As we start to grow, it may make sense to break these out more.

**Comment by ardalis** [comment]
Sure, that makes sense. Might be some overlap but no reason some sections can't both reference the same content if that's helpful.
