### ISSUE TITLE
Search -> Focus

### ISSUE THREAD

**Issue by ardalis** [ardalis/DevIQ-gatsby#340]
After clicking on Search give the search textbox focus so one can start typing immediately

**Comment by sadukie** [comment]
I have this working on the blog. However, when I added it, there was an accessibility issue that said not to use autoFocus. Might need to see what the proper approach is.

**Comment by ardalis** [comment]
Cool. I used your same approach for ardalis.com. Hasn't deployed yet but hopefully soon.
