### ISSUE TITLE
Bug: Refactoring Fundamentals link on Code Smells page is dead

### ISSUE THREAD

**Issue by djfuzzy** [ardalis/DevIQ-gatsby#462]
The link (https://www.pluralsight.com/courses/refactoring-fundamentals) to a Refactoring Fundamentals course on Pluralsight on the [Code Smells](https://deviq.com/antipatterns/code-smells) page is dead. I could not find an alternative link after a quick search.

**Comment by KyleMcMaster** [comment]
I believe the updated link should point to [https://www.pluralsight.com/courses/refactoring-csharp-developers](https://www.pluralsight.com/courses/refactoring-csharp-developers), @ardalis can you confirm?

**Comment by ardalis** [comment]
Yes that's the one now, thanks.

Pluralsight does a poor job of keeping links working.
