### ISSUE TITLE
Architecture: Add Clean Architecture

### ISSUE THREAD

**Issue by sadukie** [ardalis/DevIQ-gatsby#483]
Include these links

```
[Clean Architecture course](https://bit.ly/3WQ8Cvq)
[Clean Architecture with .NET 8 webinar](https://mailchi.mp/nimblepros/clean-architecture-dotnet-8-recording)

**Comment by G0x209C** [comment]
Why use a bitly and not the actual URL it goes to?

https://academy.nimblepros.com/p/intro-to-clean-architecture#sq_hrln40vsft

**Comment by sadukie** [comment]
> Why use a bitly and not the actual URL it goes to? Shady ಠ_ಠ
> 
> `[Clean Architecture course](https://academy.nimblepros.com/p/intro-to-clean-architecture)`

Bitly gives us shorter URLs for social media and better analytics.
